### ISSUE TITLE
Install error: pkg error: - mysql-connector-java

### ISSUE THREAD

**Issue by victorbrca** [leandroscardua/iocage-plugin-guacamole#2]
I'm getting the following error when trying to install the plugin on TrueNAS Core 13.0-U6.1. 

```
Error: Guacamole had a failure Exception: RuntimeError Message: pkg error: - mysql-connector-java : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed
```

When I check the current json file I see that it's set to `"release": "13.2-RELEASE"`, which is different than what's in the repo.

**Comment by leandroscardua** [comment]
I just merge your PR.
Thank you for your support
